### ISSUE TITLE
Code quality

### ISSUE THREAD

**Issue by st3no** [mayuso/JMarkPad#42]
I think it is appropriate to add a tool to check the quality of the code, since some functions are complex, I think that an instrument of this type can help us simplify the code and make it more performing.

If you think about it this way, but without knowing which one to choose, I recommend **[Code Climate](https://github.com/marketplace/code-climate)**.

**Comment by mayuso** [comment]
Not sure about this.

Code quality is important, but we don't have a huge code base, and we don't have huge performance issues, so I don't see it as a priority.

I'll think about it but I am currently working on migrating other projects from Java 8 to OpenJDK 11. I might also do it with JMarkPad and make a 2.0 release instead of 1.2.

Maybe for 2.1
